# Generated by Django 6.0.3 on 2026-03-31 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traiteur", "0002_remove_traiteur_service_remove_traiteur_specialite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraiteurProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=150)),
                ("categorie", models.CharField(blank=True, max_length=100)),
                (
                    "annee_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("photo", models.URLField(blank=True, null=True)),
                ("services", models.ManyToManyField(blank=True, to="traiteur.service")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
