# Generated by Django 6.0.3 on 2026-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
        ("traiteur", "0002_remove_traiteur_service_remove_traiteur_specialite"),
    ]

    operations = [
        migrations.AddField(
            model_name="traiteurprofile",
            name="specialites",
            field=models.ManyToManyField(blank=True, to="traiteur.specialite"),
        ),
    ]
