# Generated by Django 6.0.3 on 2026-03-31 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Service", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Specialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialite", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Traiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomcomplet", models.CharField(max_length=100)),
                ("specialite", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("adresse", models.CharField(max_length=200)),
                ("estactif", models.BooleanField()),
                ("email", models.EmailField(max_length=254)),
                ("datedecreation", models.DateField(default=django.utils.timezone.now)),
                ("image", models.URLField(blank=True, null=True)),
                ("telephone", models.CharField(max_length=20)),
                ("annee_experience", models.IntegerField(default=0)),
                ("service", models.CharField(max_length=100)),
                ("Service", models.ManyToManyField(to="traiteur.service")),
                ("Specialite", models.ManyToManyField(to="traiteur.specialite")),
            ],
        ),
    ]
