# Generated by Django 6.0.3 on 2026-03-30 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomcomplet", models.CharField(max_length=100)),
                ("specialites", models.TextField()),
                ("description", models.TextField()),
                ("adresse", models.CharField(max_length=200)),
                ("estactif", models.BooleanField()),
                ("email", models.EmailField(max_length=254)),
                ("datedecreation", models.DateField(default=django.utils.timezone.now)),
                ("image", models.URLField()),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
    ]
