# Generated by Django 6.0.3 on 2026-03-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traiteur", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traiteur",
            name="service",
        ),
        migrations.RemoveField(
            model_name="traiteur",
            name="specialite",
        ),
    ]
