# Generated by Django 6.0.3 on 2026-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traiteur", "0002_remove_traiteur_service_remove_traiteur_specialite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Langue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("langue", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="traiteur",
            name="langue",
            field=models.ManyToManyField(to="traiteur.langue"),
        ),
    ]
